### ISSUE TITLE
set required symfony/console version to ~2.5

### ISSUE THREAD

**Issue by BlackGh0st** [phpecc/phpecc#101]
The required symfony/console version should be the same as the minimum version of composer[1] to prevent conflicts with other projects/dependency.

For example, a project with the dependency symfony/symfony v2.5.12 doesn't allow symfony/console v2.6
 - [1] https://packagist.org/packages/composer/composer

**Comment by aztech-dev** [comment]
Not sure what you mean. I may be wrong, but the project doesn't have composer as a dependency, so it shouldn't conflict with composer's requirement.

Current Symfony LTS is 2.7, so I'd actually favor a bump to that version rather than a downgrade. But in the end, as long as the current commands still work with ~2.5, I'm not religiously opposed to your suggestion :)

**Comment by btcdrak** [comment]
@aztech-dev ACK

**Comment by aztech-dev** [comment]
@btcdrak ACK for 2.7 or 2.5 ?

**Comment by btcdrak** [comment]
2.7

**Comment by btcdrak** [comment]
We need to check the changelog, make sure there arent any BC breaks first, but in principal, it should be bumped up.

**Comment by aztech-dev** [comment]
Allright, I'll work on it this week if my schedule allows it.

**Comment by BlackGh0st** [comment]
Hmm well I see, so this might be a stupid idea, but would it be possible to split this project to a cli-part and a library-part ? (I really don't need the cli-part)

My current problem is, I can't use this library because of the minimum requirement of symfony/console 2.6 (I surely should think about a upgrade to symfony 2.7 but that's currently not possible)

**Comment by btcdrak** [comment]
@BlackGh0st it seem bizarre to have a project with a dependency on the package manager...

**Comment by BlackGh0st** [comment]
My dependency is symfony, not composer, I just wanted to make clear that composer also doesn't have the newest symfony/console as minimum requirement

**Comment by btcdrak** [comment]
@BlackGh0st I am sorry but 2.5 is actually end of life for support http://symfony.com/doc/current/contributing/community/releases.html we prefer LTS wherever possible.

**Comment by BlackGh0st** [comment]
okey I understand :) thanks anyway :D so I really should think about a upgrade ;D

**Comment by aztech-dev** [comment]
Ok. Your initial post made it seem like a dependency on composer was the issue.

I'm not against splitting the lib and the CLI in two separate projects, but it wouldn't be done until next major release as it's a BC break.

**Comment by mdanter** [comment]
+1 for splitting out the core libs from the CLI
