### ISSUE TITLE
Split core lib from CLI

### ISSUE THREAD

**Issue by BlackGh0st** [phpecc/phpecc#103]
As a result of a small discussion on the issue https://github.com/phpecc/phpecc/issues/101, I would suggest to split the core lib from the CLI. The main reason for this split is that the library as itself doesn't need the CLI-part (symfony/console) and could cause a non-essential dependency conflict.

**Comment by Spomky** [comment]
+1

**Comment by aztech-dev** [comment]
+1

**Comment by btcdrak** [comment]
There is certainly no harm in it.

**Comment by afk11** [comment]
+1

**Comment by btcdrak** [comment]
I've created a new repository for it https://github.com/phpecc/console

**Comment by afk11** [comment]
PR moving console related code/tests: https://github.com/phpecc/console/pull/1

**Comment by afk11** [comment]
Looks like this is happening with Laravel at the moment (https://github.com/Bit-Wasp/bitcoin-php/issues/295) Sooner we tag the better :)

**Comment by afk11** [comment]
This is fixed in master, just waiting on #157.
