### ISSUE TITLE
Adopt a mailing list or IRC channel? 

### ISSUE THREAD

**Issue by afk11** [phpecc/phpecc#104]
I'd like to propose we use an IRC channel or mailing list for lighter discussions about the direction of the project.

This follows some recent work I have done around X509 using php-ecc (CSR/Certificate capabilities) - I'd quite like to create a new repository for it under phpecc, similar to what we're doing with the console application.

A mailing list or IRC channel might be best for project wide decisions, and general discussion.

**Comment by mdanter** [comment]
+1 to channel as long as it provides clear value to the community (what about two channels, phpecc, and phpecc-dev)

+1 to CSR/Cert related functionality, please make sure it doesn't introduce unnecessary third party dependencies on core pieces

**Comment by afk11** [comment]
@mdanter Indeed - I'd like to avoid raising an issue on this repository when a general discussion could be had elsewhere.

At the moment it requires only PHPECC and it's dependencies, I am aiming to keep it fairly self-contained.

**Comment by mdanter** [comment]
It looks like there's a phpecc channel on freenode.

**Comment by afk11** [comment]
That was me, though I didn't want to advertise something unofficial. It's registered now, so hope to see some of you there. A mailing list may also be useful for announcing API breaks + major features, but mostly interested in a place to chat.

**Comment by mdanter** [comment]
phpecc on freenode is official, thanks @afk11
