### ISSUE TITLE
I am unable to install laravel 5

### ISSUE THREAD

**Issue by skt0108** [phpecc/phpecc#109]
Hi there

when i install laravel 5. i am getting error "installation failed, deleting ./composer.json"

i don't know what happening there.

So please help me. 

i look forward hear from you!
Kinds Regard
alok

**Comment by aztech-dev** [comment]
Can you provide more details on the error ? This library is absolutely unrelated to Laravel, so it's hard to see/understand what may be going on here....

**Comment by skt0108** [comment]
hi 

thanks for your message.

i found my issue and i solve it.
