### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by skt0108** [phpecc/phpecc#110]
hi
when i create a new table getting error.

#1089 - incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys

it is happening when i select field  A_I. if don't use A_I field. it is working. I am looking for permanent solutions. Please help me.
  
i am using win8.1 and xampp server. 

Thank you in advance for your time.

thanks
Alok

**Comment by aztech-dev** [comment]
Hello,

This library is for elliptic curve cryptography. You should instead ask your question on Stackoverflow.com rather than here.
