### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by Minishlink** [phpecc/phpecc#111]
Hi :)

First of all, thanks for your work on this library.

I would like to implement [this particular use case](https://tools.ietf.org/html/draft-thomson-webpush-encryption-00#section-3) (Web Push API) for my library [WebPush](https://github.com/Minishlink/web-push).

I'm new to cryptography. I'm not sure if you've written this library for people with a minimum of experience with cryptography or not, but I tried to do it anyway.

So far, I have written this:
```php
$localCurveGenerator = EccFactory::getNistCurves()->generator256();
$localPrivateKey = $localCurveGenerator->createPrivateKey();
$localPublicKey = $localPrivateKey->getPublicKey();

$messages = new MessageFactory(EccFactory::getAdapter());
$message = $messages->plaintext($payload, 'sha256');

$pubKeySerializer = new PemPublicKeySerializer(new DerPublicKeySerializer());
$remotePublicKey = $pubKeySerializer->parse($userPublicKey);

$dh = $localPrivateKey->createExchange($messages, $remotePublicKey);
$salt = hash('sha256', $dh->calculateSharedKey(), true);

$cipherText = $dh->encrypt($message);

return array(
    'localPublicKey' => base64_encode($localPublicKey->getContent()), // this doesn't exist
    'salt' => base64_encode($salt),
    'cipherText' => base64_encode($cipherText->getContent()),
);
```

I have several questions:
1. I get `$salt` the way above because I naively thought it was the same as the `$key` in your `EcDH->encrypt()`. Am I right or not at all?
2. How do you get content of a `PublicKey` ? Am I right to assume I can do it by calling `getPoint()->getX()` on it? Or does this return something else?
3. In the code above `$userPublicKey` is in fact a base 64 encoded string of the user public key. One example is: `BKD9anmcirmuG9J4wlPAmezLpqvrBd3mD2Q680XfJNkCzjIx2AwTcUcSrBSzJI9eCkk61ZGbjAglCoPQO9kh0g4=`. The parser throws a "Invalid data.". Do you know why ?

**Comment by afk11** [comment]
I haven't worked with that API before, but some advice all the same:

First, I'd warn against using the encryption feature of the EcDH class. Hashing the shared public key's X point is often an optional step, so in doing this it may produce data incompatible with your browser. Calling mcrypt is a tiny step to do yourself, better off doing so to be sure!

1. $salt appears to be random for each request. 
https://tools.ietf.org/html/draft-nottingham-http-encryption-encoding-00#section-3.2
    PRK = HMAC-SHA-256(salt, IKM)
Salt is used along with the shared key (IKM, probably the shared key pack()'d) to produce the actual encryption key for the message.

2. What do you mean content? The point, it's values? or it's binary representation? 

3. https://github.com/phpecc/phpecc/blob/master/src/Serializer/PublicKey/PemPublicKeySerializer.php
Your public key isn't PEM. It decodes to this, which is just an uncompressed point. It's not quite DER. Just a byte of 0x04, and the serialized X and Y point. This is just another representation, less verbose than the DER format calls for. 

Prefix: 04
X: A0FD6A799C8AB9AE1BD278C253C099ECCBA6ABEB05DDE60F643AF345DF24D9
Y: 02CE3231D80C13714712AC14B3248F5E0A493AD5919B8C08250A83D03BD921D20E

You can use the UncompressedPointSerializer to parse this after you base64 decode it.

**Comment by Minishlink** [comment]
Thanks for your explanation, it was very helpful.

So I followed your advice and didn't use the encryption feature of the EcDH class. First I thought of using mcrypt (just like phpecc), but I saw that it was a deprecated library since 2007 and that it was recommended to use openssl now, so I used openssl.

For 2., I meant the binary representation. I used the UncompressedPointSerializer to get it. :)

So I've now written [this code](https://github.com/Minishlink/web-push/blob/8d55f0ae6406547fd0a3247e1979982eb77e099a/src/WebPush.php#L141).

I have one last question related to phpecc. In phpecc, computing the shared secret sums up to the following line in my code:
```php
/** @var $userPublicKeyObject PublicKey */
/** @var $localPrivateKeyObject PrivateKey */
$sharedSecret = $userPublicKeyObject->getPoint()->mul($localPrivateKeyObject->getSecret())->getX();
```
Here, why do we get only the X value ? And not the X and Y value with a prefix just like the public keys ?

**Comment by afk11** [comment]
Nice to see things are coming along! I hadn't heard that about mcrypt, I'll dig some more! I avoid openssl af

https://github.com/Minishlink/web-push/blob/8d55f0ae6406547fd0a3247e1979982eb77e099a/src/WebPush.php#L161
Probably not meant to hash the base64 representation, but the raw binary output of `openssl_random_pseudo_bytes`. 

Same goes for the X coordinate - convert to binary, remembering to pad to 64 characters (in hex), ie 32bytes (which is 256bit)
    $binarySecret = str_pad( $math->decHex($sharedSecret), 64, '0', STR_PAD_LEFT);

You'd best consult the DH specification. My thoughts are: Y can be recovered from X, so that would be bad. It doesn't add anything besides potential problems, whereas with just X, it makes the same assumptions as straight ECC.

**Comment by Minishlink** [comment]
Ok, so it appears that GCM mode is supported neither by mcrypt nor by openssl so what I want to achieve is not possible at the moment.

Maybe phpecc should hint to use [defuse/php-encryption](https://github.com/defuse/php-encryption) and deprecate the encrypt/decrypt functions ? (it's not what I'm aiming for but would certainly be fit for most users)

Anyway, thanks again for the useful info, I'm closing this issue since I don't have questions anymore. :)

**Comment by Minishlink** [comment]
Hi @afk11, I have a base 64 encoded private/public key pair and I would like to use them in phpecc for testing purposes.

However, phpecc requires to know the "secret multiplier" in order to create the PrivateKey object, and I don't know how to compute it. (I would use phpecc to do that, ha!)
Moreover, the `UncompressedPointSerializer` seems to give me a Point, but I don't find any way to create a PrivateKey object from a Point like there is for a PublicKey object.
Finally, `DerPrivateKeySerializer` doesn't seem to like the input (base 64 decoded into binary) as it gives me the following error `Uninitialized string offset: 32`. I'm sure this is because DER format is something else than this pure binary, but I honestly don't know what the format is, even though I've searched on Google and GitHub...

For info, the key pair looks like this:
  * private: `Dt1CLgQlkiaA+tmCkATyKZeoF1+Gtw1+gdEP6pOCqj4=`
  * public: `BG3OGHrl3YJ5PHpl0GSqtAAlUPnx1LvwQvFMIc68vhJU6nIkRzPEqtCduQz8wQj0r71NVPzr7ZRk2f+fhsQ5pK8=`

So if you could point me to the right direction, it would be much appreciated. :)
  * If I should use `DerPrivateKeySerializer`, how do I convert my simple base 64 encoded string to DER encoded data?
  * If I should use the PrivateKey constructor, how do I compute the secretMultiplier needed from the private/public key pair ?

**Comment by afk11** [comment]
DER private keys are just one possible encoding for things depending on necessity. It's useful when a protocol needs to support a variety of keys/curves - so more data is included. 

Your private key in base64 is just the 256-bit key encoded in binary, so you aren't dealing with DER here. Converting that data to hex, and subsequently to decimal will give you your scalar!

With the public key, you were correct to use UncompressedPointSerializer, but again it's just a matter of encoding: 

```php
use Mdanter\Ecc\EccFactory;
use Mdanter\Ecc\Serializer\Point\UncompressedPointSerializer;

$math = EccFactory::getAdapter();
$nist = EccFactory::getNistCurves();
$curve = $nist->curve256();
$generator = $nist->generator256();

$privateBase64 = 'Dt1CLgQlkiaA+tmCkATyKZeoF1+Gtw1+gdEP6pOCqj4=';
$publicBase64 = 'BG3OGHrl3YJ5PHpl0GSqtAAlUPnx1LvwQvFMIc68vhJU6nIkRzPEqtCduQz8wQj0r71NVPzr7ZRk2f+fhsQ5pK8=';

// Deserialize raw private key
$privateHex = bin2hex(base64_decode($privateBase64));;
$scalar = $math->hexDec($privateHex);
$privateKey = $generator->getPrivateKeyFrom($scalar);

// Deserialize raw public key
$pointSerializer = new UncompressedPointSerializer($math);

$publicHex = bin2hex(base64_decode($publicBase64));
$point = $pointSerializer->unserialize($curve, $publicHex);
$publicKey = $generator->getPublicKeyFrom($point->getX(), $point->getY(), $generator->getOrder());

var_dump($privateKey);
var_dump($publicKey);

// Encoding again:

$encodedPriv = base64_encode(hex2bin(str_pad($math->decHex($privateKey->getSecret()), 64, '0', STR_PAD_LEFT)));
$encodedPub = base64_encode(hex2bin($pointSerializer->serialize($publicKey->getPoint())));

```

Note the encoding of the private key - don't forget to pad to the key size if you need to serialize (256 bit = 32 bytes or 64 characters in hex encoding)

**Comment by Minishlink** [comment]
Thank you for pointing out `$generator->getPrivateKeyFrom($scalar);` ! I don't know if it's common knowledge among cryptographers, but for a starter like me, it was not obvious that the `secretMultiplier` of the documentation could be in fact the private key.
Thanks again. :)
