### ISSUE TITLE
Avoid strlen() and substr()

### ISSUE THREAD

**Issue by paragonie-scott** [phpecc/phpecc#115]
https://secure.php.net/manual/en/mbstring.overload.php

> In short, only use mbstring.func_overload if you are 100% certain that nothing on your site relies on manipulating binary data in PHP.

If you're doing crypto, then you're manipulating binary data. Fortunately, there's a workaround.

I added a utility in #114 so if you merge that, then you can begin using `BinaryString::length()` instead of `strlen()` and `BinaryString::substring()` instead of `substr()`.

**Comment by afk11** [comment]
Ping @aztech-dev  @Spomky @mdance @btcdrak

**Comment by Spomky** [comment]
I read some articles about this topic and it seems that this extension should be used instead of the usual PHP string methods.
The PR #114 introduces an easy way to use this extension when available, but IMHO the code could be optimized.

**Comment by Spomky** [comment]
#114 has been merged, but this issue has not been taken into account.
Recently I discovered and immediatly adopted the Symfony Polyfills libraries. One of these libraries provides easy to use MBString methods even if the extension is not available:

Just add `symfony/polyfill-mbstring` as a required dependency and use `mb_strlen` or `mb_substr`.

**Comment by afk11** [comment]
The polyfill do add something, but we'll still need constant time string operations all the same. Not to reinvent this stuff ourselves, I think paragonie have published some code to that end.

**Comment by paragonie-scott** [comment]
Yeah, [constant_time_encoding](https://github.com/paragonie/constant_time_encoding) (RFC 4648 without cache-timing leaks) also comes with a `Binary` class that solves this problem.
