### ISSUE TITLE
curve25519 and curve448 support

### ISSUE THREAD

**Issue by Spomky** [phpecc/phpecc#117]
The [RFC7748](https://tools.ietf.org/html/rfc7748) introduces two new curves: curve25519 and curve448.

Do you plan to add a support for these two curves?

**Comment by afk11** [comment]
They would be nice, we'd have to check the algorithm is suitable. It might be more effort than adding it to the CurveFactory, but worthwhile all the same.

**Comment by Spomky** [comment]
Great news.
I found [that repositories](https://github.com/encedo) that provide Ed25519 implementations. That could help you.

**Comment by afk11** [comment]
Interesting, I'll give that a look! I read over the RFC the other day, it seems to have lots of details not seen in PHPECC today. It wouldn't be as straightforward as I would have hoped!

The extension is probably faster than we'll be able to pull off in pure PHP, but I'll have to check it later!

**Comment by Spomky** [comment]
Well... yes you are right, this library will never be as fast as an extension.
I decided to try the extension mentioned above and the first tests that I ran gave me good results.

**Comment by witdiarta** [comment]
Please tech me how to create "public key" from "private key" because there is not documentation about that :(

**Comment by afk11** [comment]
@witdiarta Please don't spam requests for help on old issues. You should also spend 5 minutes to read the code first: https://github.com/phpecc/phpecc/blob/master/src/Crypto/Key/PrivateKeyInterface.php#L39 and https://github.com/phpecc/phpecc/blob/master/src/Crypto/Key/PrivateKey.php

**Comment by paragonie-scott** [comment]
I've implemented [X25519 and Ed25519 in sodium_compat](https://github.com/paragonie/sodium_compat) if you'd like to either reference that implementation (or just add sodium_compat as a dependency).

Take note that [it has yet to be audited](https://github.com/paragonie/sodium_compat/issues/8) and therefore should be viewed as experimental until we can get that done.

**Comment by paragonie-scott** [comment]
We've tagged [v1](https://github.com/paragonie/sodium_compat/releases/tag/v1.0.0) so it may be worth adopting sodium_compat to fulfill your needs for Curve25519.

**Comment by Spomky** [comment]
Closing as the curves Ed25519/X25519 are available by other means (libCrypto or PHP 7.2).
An implementation of the curves Ed448 and X448 is still missing, but it looks like these curves are not widely used.
