### ISSUE TITLE
Length of signature

### ISSUE THREAD

**Issue by gaminn** [phpecc/phpecc#176]
I use secp256k1 private key to sign a message. 

`       $adapter = EccFactory::getAdapter();
        $generator = EccFactory::getNistCurves()->generator256();
        $useDerandomizedSignatures = true;
        $algorithm = 'sha256';
        ## You'll be restoring from a key, as opposed to generating one.
        $pemSerializer = new PemPrivateKeySerializer(new DerPrivateKeySerializer($adapter));
        $keyData = file_get_contents('priv.pem');
        $key = $pemSerializer->parse($keyData);
        $signer = new Signer($adapter);
        $hash = $signer->hashData($generator, $algorithm, $messageToSign);
        # Derandomized signatures are not necessary, but can reduce
        # the attack surface for a private key that is to be used often.
        if ($useDerandomizedSignatures) {
            $random = \Mdanter\Ecc\Random\RandomGeneratorFactory::getHmacRandomGenerator($key, $hash, $algorithm);
        } else {
            $random = \Mdanter\Ecc\Random\RandomGeneratorFactory::getRandomGenerator();
        }
        $randomK = $random->generate($generator->getOrder());
        $signature = $signer->sign($key, $hash, $randomK);
        $serializer = new DerSignatureSerializer();
        $serializedSig = $serializer->serialize($signature);
        return base64_encode($serializedSig);`

This returns 96 byte long base64 encoded string, that is 72 bytes of binary data. However, secp256k1 signature should be 64 bytes long. How to get 64 bytes long signature?

I want to pass this signature to CryptoPP C++ library where it is going to be verified by public key. Obviously, the verification always fails when I pass incorrect signature length to my CryptoPP C++ program.

**Comment by gaminn** [comment]
I figured it out. PHPECC uses DER encoding of ASN1 structure. For me, it is sufficient to convert signature (r and s integers) to binary data.
`$serializedSig = $serializedSig = gmp_export($signature->getR()) . gmp_export($signature->getS());
 return base64_encode($serializedSig);`

**Comment by afk11** [comment]
Great stuff, glad to see you got it sorted.
