### ISSUE TITLE
how to create public key

### ISSUE THREAD

**Issue by witdiarta** [phpecc/phpecc#177]
Hello every one, please add the documentation which tell about how to "create public key" because it's will be awesome fist php lib which tell about Elliptic Curve if the tutorial to be completed. thanks :)

**Comment by jonathanpmartins** [comment]
Im really exited for php 7.1 release for production, so I can migrate all my scripts using this lib. Right now I dont know how to answer your question, but I really feel to need to make this point! hehehhe

**Comment by witdiarta** [comment]
I think it would be more famous lib if the documentation is complete let alone just a little lib on elliptic Curver outstanding, in fact only less documentation about making a public key so that a newbie like me can learn to complete

**Comment by afk11** [comment]
@witdiarta There's an example using a serializer in the readme, did you see that? The PrivateKey also has a function if you happen to have that. 

I'm not sure the library *should* have a tutorial on elliptic curves, as there are great resources online, but also since the people who would need it are most likely to misuse them. 

@jonathanpmartins The library should be compatible, but ending support for 5.x means we can have strict types and other goodies. Why 7.1 in particular?

**Comment by afk11** [comment]
> Please tech me how to create "public key" from "private key" because there is not documentation about that :(

@witdiarta Please don't spam requests for help on old issues. You should also spend 5 minutes to read the code first: https://github.com/phpecc/phpecc/blob/master/src/Crypto/Key/PrivateKeyInterface.php#L39 and https://github.com/phpecc/phpecc/blob/master/src/Crypto/Key/PrivateKey.php

**Comment by witdiarta** [comment]
@afk11, i'm so sorry about that, i'v delete that comment. btw i've read it many times but still do not know how to do, maybe because of my knowledge about OOP is less i can't/get idea about that, please can you give some clue or PHP code, thanks  for your support :)

**Comment by afk11** [comment]
What have you got so far? If you have a PrivateKey you can just call `$privateKey->getPublicKey()` on it

**Comment by witdiarta** [comment]
@afk11 This is my code for createing private key and public key in file but when i try to verify signature it's error 
```
        $adapter 				= EccFactory::getAdapter();
		$generator				= EccFactory::getNistCurves()->generator384();
		$private 				= $generator->createPrivateKey();

		$privKeySerializer 		= new PemPrivateKeySerializer(new DerPrivateKeySerializer($adapter));
		$privkey 				= $privKeySerializer->serialize($private);

		$public					= $private->getPublicKey();
		$pubKeySerializer 		= new PemPrivateKeySerializer(new DerPrivateKeySerializer($adapter));
		$pubkey 				= $pubKeySerializer->serialize($public);

		openssl_pkey_export_to_file($privkey, './certs/ecdsa-pri.pem');
		file_put_contents('./certs/ecdsa-pub.pem', $pubkey);
```
That reason i ask to you how to create public key from private key, because i still get error for verify signature thanks for supporting

**Comment by afk11** [comment]
$pubKeySerializer       = new PemPrivateKeySerializer(new DerPrivateKeySerializer($adapter));

There are PemPublicKey & DerPublicKey classes for the public key. Maybe post the error and your signature verification code?

**Comment by witdiarta** [comment]
Oh my God i miss it :( , thanks @afk11 my code is work now :)

**Comment by afk11** [comment]
Great to hear!
