### ISSUE TITLE
Tag a v0.4.1 release for resolving Composer conflict

### ISSUE THREAD

**Issue by Minishlink** [phpecc/phpecc#179]
Hi,

May someone tag a new minor release please? The [last commit](https://github.com/phpecc/phpecc/commit/192903b8a8ec630c4e51d609c85485807c3029ae) fixes a Composer conflict with a major release of Symfony (3.1) and this library.

**Comment by afk11** [comment]
Hi, yeah I will do this in a couple of hours.

**Comment by Minishlink** [comment]
Thanks!

**Comment by afk11** [comment]
Sorry for the delay: https://github.com/phpecc/phpecc/releases/tag/v0.4.1
