### ISSUE TITLE
UncompressedPointSerializer appears to have unused dependency on GmpMathInterface

### ISSUE THREAD

**Issue by johanderuijter** [phpecc/phpecc#180]
After the following two commits ( [1](https://github.com/phpecc/phpecc/commit/32b0a326049f10880e89fe953b41396c112e1ab1#diff-fa26efe85c516b50cae3591e981e6db1), [2](https://github.com/phpecc/phpecc/commit/17e34b47448737a024b3bae41e631283ae5c991a#diff-fa26efe85c516b50cae3591e981e6db1) ) the [UncompressedPointSerializer](https://github.com/phpecc/phpecc/blob/master/src/Serializer/Point/UncompressedPointSerializer.php) no longer uses the GmpMathInterface but still has it as a dependency.

Was there a reason for keeping it or is this an oversight?

I'd be happy to make a pull request to remove it, but given the nature of the library aren't sure you'd want me to. To me it seems like a harmless enough change, but i'm not exactly an expert in the subject matter.

**Comment by johanderuijter** [comment]
Or should it be using the `decHex`/`hexDec` methods from the GmpMath like it was before the change to Gmp?

**Comment by afk11** [comment]
Sorry for the delay, not sure how I missed these! Feel free to submit the PR if you have time, I'll mark this for the next major release anyway

**Comment by johanderuijter** [comment]
No problem! Thx for maintaining this library, it's helped me a lot!

Pull request made: #187
