### ISSUE TITLE
PemLoader

### ISSUE THREAD

**Issue by kotarCreative** [phpecc/phpecc#183]
Hi, 

I do not see the PemLoader file anywhere in your source code. Your documentation has it as a use statement though. `use Mdanter\Ecc\File\PemLoader;` Is this legacy or am I missing something?

Thanks for the help.

**Comment by afk11** [comment]
Might be legacy documentation, think it was removed because it just wrapped file_get_contents?

**Comment by kotarCreative** [comment]
Ah ok that makes more sense. So the pemSerializer takes in a string then?

David

**Comment by afk11** [comment]
Yeah, think `*Serializer::parse()` always takes a string, serialize is typed with the interface
