### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by afk11** [phpecc/phpecc#185]
The current idea is drop PHP 5.6 & HHVM support in v0.5. There isn't much calling for a BC break at the moment, so it'd be neat if v0.5 was compatible with the v0.4 API besides the new type hinting features. 

That said, I could say the same about PHP7.1 (released in December) and a hypothetical v0.6.

**Comment by johanderuijter** [comment]
If you want any, I'd be happy to help with this. Just let me know if you have any special requests. 

In case you can use the help, are we talking just type declarations or also return types? Would you prefer smaller commits / pr's or bigger / everything at once ones?

**Comment by afk11** [comment]
Cool! I made a start here (https://github.com/phpecc/phpecc/pull/184) which has a good deal of the declarations & return types done, there's probably more to do. 

Big PR's are fine so long as the scope of the changes remain narrow, so big commits are fine, just make sure you're not doing 10 different things. Where possible I avoid committing broken commits (tests should pass), or just feel free to commit them and squash/amend later to clarify

**Comment by afk11** [comment]
Sorry for the delay on this, I realized a short while ago I hadn't made a tagged release on since PHP7 had hit master. 

I'm pleased to say we have a new shiny PHP >=7 only branch on v0.5.0!
