### ISSUE TITLE
Question: pubkey  / pubpoint validation

### ISSUE THREAD

**Issue by moe123** [phpecc/phpecc#203]
Hello @afk11 ,

in the near future, do you plane to implement a `pubkey against a point checking` routine ? at least for short weierstrass curve types ?

Thank you.

**Comment by moe123** [comment]
closing, ok ; it exists !  apologies ; i.e isValid / contains.

**Comment by afk11** [comment]
To be absolutely sure, you should try this:
```
try {
    $cert_key->getPublicKeyFrom($tls_pt->getX(), $tls_pt->getY());
    return true;
} catch (\Exception $e) {
    return false;
}
```

After testing some of this recently I noticed the API should be clearer about what is a safe point validation routine. The most certain test is creating the PublicKey instance - if that works, you can consider the point valid for the curve/generator.

**Comment by moe123** [comment]
Hello @afk11 , thank you.

Yes, for that concern: matching/verifying self-signed certs / extracting signature and keys ; I am juggling between `phpecc` , `phpseclib` and in a last resort `the openssl extension` i.e ; being able to handle all my needs. Hopefully 8-D, I wrote an abstraction layer, hence dispatching on factory/strategy objects ; it's not the most efficient in terms of performances... but at least solid and enough clean to make it evolve over time.
