### ISSUE TITLE
Can't exchange with Windows Implementation

### ISSUE THREAD

**Issue by Daniel0r** [phpecc/phpecc#206]
Hi,

Our customer is trying to do an exchange with us using your library.  However, I'm having a hard time to come up with sample code to use your library to do the exchange.  The Shared Secrets generated match 1 out of 4-5 times.  Is it possible for you to help identify what needs to be tuned on PHP side to resolve the issue?
Assuming that you have something like Visual Studio or RoslynPad installed.
Steps to reproduce the issue:
1) Run the PHP code.  The first output is the public key in xml format, Don't worry about the 2nd part for now.
2) Copy the C# code to Visual Studio or RoslynPad.
3) Copy the XML from step 1 into C# code
4) Run the C# code.  This creates the server key, import the client key and export the server public key xml and SharedSecret.
5) Copy the server public key back to PHP side and run the code again.  
6) Check the shared secret.  One out of 4/5 times would match.
Thanks for your help.

-----------------------------------------------------
using System;
using System.Security.Cryptography;
					
public class Program
{
	const string ClientPublicKeyString = @"
		
<ECDHKeyValue xmlns='http://www.w3.org/2001/04/xmldsig-more#'><DomainParameters><NamedCurve URN='urn:oid:1.3.132.0.35' /></DomainParameters>
        <PublicKey><X Value='1336359245332636916550376615423622380926637341586357753288832285610268853362962575832284809873305381126333054782084357853619276576847906567112819268736281129' xsi:type='PrimeFieldElemType' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' />
        <Y Value='2128428628198652632216376304388371447719978432780420698196369804228250676787846222242268470702668235047076489753258843511866612682116219320256928088025630166' xsi:type='PrimeFieldElemType' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' /></PublicKey></ECDHKeyValue>

		";
	public static void Main()
	{
		using (ECDiffieHellmanCng serverKey = new ECDiffieHellmanCng(521))
		{
			serverKey.KeyDerivationFunction = ECDiffieHellmanKeyDerivationFunction.Hash;
			serverKey.HashAlgorithm = CngAlgorithm.Sha256;
			
			
			using (ECDiffieHellmanCng clientKey = new ECDiffieHellmanCng())
			{
				clientKey.FromXmlString(ClientPublicKeyString, ECKeyXmlFormat.Rfc4050);
				var sharedSecret = serverKey.DeriveKeyMaterial(clientKey.PublicKey);
				Console.WriteLine(serverKey.PublicKey.ToXmlString().Replace("\"", "'").Replace("\r","").Replace("\n", ""));
				Console.WriteLine(Convert.ToBase64String(sharedSecret));
			}
		}
		
	}
// Program.Main();  // need this uncommented and outside fot if you are using RoslynPad
}

-----------------------------------------------------
```php
<?php
require 'vendor/autoload.php';

use Mdanter\Ecc\Crypto\EcDH\EcDH;
use Mdanter\Ecc\Crypto\Key\PrivateKey;
use Mdanter\Ecc\EccFactory;
use Mdanter\Ecc\Tests\AbstractTestCase;

class EcDHTest 
{
    
    private static function _keyDerivationFunction($math, $sharedSecret)
    {
        $binary = $math->intToString($sharedSecret);
        $hash = hash('sha256', $binary, true);
        return $hash;
    }
    const ECDHKeyValueXml = '<ECDHKeyValue xmlns=\'http://www.w3.org/2001/04/xmldsig-more#\'><DomainParameters><NamedCurve URN=\'urn:oid:1.3.132.0.35\' /></DomainParameters>
        <PublicKey><X Value=\'%s\' xsi:type=\'PrimeFieldElemType\' xmlns:xsi=\'http://www.w3.org/2001/XMLSchema-instance\' />
        <Y Value=\'%s\' xsi:type=\'PrimeFieldElemType\' xmlns:xsi=\'http://www.w3.org/2001/XMLSchema-instance\' /></PublicKey></ECDHKeyValue>';

    public static function test()
    {
        $generator = EccFactory::getNistCurves()->generator521();
        $adapter = EccFactory::getAdapter();

        $secretString = '2219285025076587881734163944765951664949675186777403178574059299188501213924848514092359154488536820511932392126399578571170916333994980346156346512122286111';
        $secretMultipler = gmp_init($secretString,10);

        $clientPrivateKey = new PrivateKey($adapter, $generator, $secretMultipler);
        $clientPublicKeyPoint =  $clientPrivateKey->getPublicKey()->getPoint();
		
        $clientKeyXValue = $adapter->toString($clientPublicKeyPoint->getX());
        $clientKeyYValue = $adapter->toString($clientPublicKeyPoint->getY());
        $clientPublicKeyString = sprintf(self::ECDHKeyValueXml, $clientKeyXValue, $clientKeyYValue);

        echo $clientPublicKeyString.PHP_EOL;
		       
        $serverKeyXmlString =         
        "<ECDHKeyValue xmlns='http://www.w3.org/2001/04/xmldsig-more#'>  <DomainParameters>    <NamedCurve URN='urn:oid:1.3.132.0.35' />  </DomainParameters>  <PublicKey>    <X Value='2360287871593216054639727297000139410735975991383946792587574375395567008787898275664076442701177077792683082940158620241863228480737934715630343555394812116' xsi:type='PrimeFieldElemType' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' />    <Y Value='4899865605758691859200024481492097356032998898870250779826703182837866329911090999699106586233237375790802844071992235711729318160715630051514409565922297935' xsi:type='PrimeFieldElemType' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' />  </PublicKey></ECDHKeyValue>"
        ;

        $serverKeyXml = (new SimpleXMLElement($serverKeyXmlString))->{'PublicKey'};
		$serverKeyXValueString = $serverKeyXml->{'X'}['Value']->__ToString();
		$serverKeyYValueString = $serverKeyXml->{'Y'}['Value']->__ToString();
		$serverKeyXValue = gmp_init($serverKeyXValueString, 10);
		$serverKeyYValue = gmp_init($serverKeyYValueString, 10);

		$serverPublicKey = $generator->getPublicKeyFrom($serverKeyXValue, $serverKeyYValue, $generator->getOrder());

		$ecdh = $clientPrivateKey->createExchange($serverPublicKey);
        $sharedSecretBeforeHash = $ecdh->calculateSharedKey();
        $sharedSecret = static::_keyDerivationFunction($adapter, $sharedSecretBeforeHash);
        echo 'Key Material '.base64_encode($sharedSecret).PHP_EOL;
    }
}

//EcDHTest::test();
```

**Comment by afk11** [comment]
Sorry, it's rather impossible to read your code, would you mind another copy paste so it's formatted? a

**Comment by afk11** [comment]
I'll check this out, but the code you wound up with for producing a shared secret (when it hashes the coordinate) likely isn't implemented exactly by the other implementation. (one of them is wrong)

You should look up the specifics of this: `ECDiffieHellmanKeyDerivationFunction.Hash;` 
to see what it does with padding, etc, cuz I imagine an RFC for this would strictly define what you do with the X coordinate to produce the shared secret. 

If anything, I should remove that snippet, as I am guessing you were just copying some code that looked reasonable...

**Comment by Daniel0r** [comment]
The ECDiffieHellmanKeyDerivationFunction.Hash is just specifing hash kdf instead of HMAC or TLS.
To simplify the problem, I wrote a Java version to compare with PHP and the results are different between Java and PHP.  First result is the same and the second result is different(wXplt1/nxI3p51x2OiNCpGiASRuS+YNA4xHHRHhTbDo= vs LutQ40zPqxrf9aduolzD5oTLcLyJlfkEcxtNIDWEBmQ=).
I really really appreciate your help on this. 
Thanks

Output:
Java
Secret   :2219285025076587881734163944765951664949675186777403178574059299188501213924848514092359154488536820511932392126399578571170916333994980346156346512122286111
Client X : 2661740802050217063228768716723360960729859168756973147706671368418802944996427808491545080627771902352094241225065558662157113545570916814161637315895999846
Client Y : 3757180025770020463545507224491183603594455134769762486694567779615544477440556316691234405012945539562144444537289428522585666729196580810124344277578376784

Server X : 4451545514874359902299158624438310022635978165655697097126344872030891198935714514315680031638033638457809873736532902539667967672541289019081100419964430099
SErver Y : 3117123408335153723030634969320433663673333908311503930938506727201806384295739721251008570149972751600305211905288827467961338284313381940052563408260641664
SharedSecret wXplt1/nxI3p51x2OiNCpGiASRuS+YNA4xHHRHhTbDo=

Secret   :2219285025076587881734163944765951664949675186777403178574059299188501213924848514092359154488536820511932392126399578571170916333994980346156346512122286111
Client X : 2661740802050217063228768716723360960729859168756973147706671368418802944996427808491545080627771902352094241225065558662157113545570916814161637315895999846
Client Y : 3757180025770020463545507224491183603594455134769762486694567779615544477440556316691234405012945539562144444537289428522585666729196580810124344277578376784

Server X : 4871355804744515205976212250393766354584896109692473021772491117721696883735035673432153598221753249992042089526706162901220401594166466831926219930877146558
SErver Y : 5026058948106722611516311449372468937826180918866645483883605206287703217468368174419063547401569795955627245203008203991092043242186043679076827428816044782
SharedSecret OOtN6gmEOiM0Wd0es1HnOK0OBhU2dSeM3nrPd3cZBiA=

PHP
Secret  : 2219285025076587881734163944765951664949675186777403178574059299188501213924848514092359154488536820511932392126399578571170916333994980346156346512122286111
Client X : 1336359245332636916550376615423622380926637341586357753288832285610268853362962575832284809873305381126333054782084357853619276576847906567112819268736281129
Client Y : 2128428628198652632216376304388371447719978432780420698196369804228250676787846222242268470702668235047076489753258843511866612682116219320256928088025630166

Server X : 4451545514874359902299158624438310022635978165655697097126344872030891198935714514315680031638033638457809873736532902539667967672541289019081100419964430099
Server Y : 3117123408335153723030634969320433663673333908311503930938506727201806384295739721251008570149972751600305211905288827467961338284313381940052563408260641664
SharedSecret wXplt1/nxI3p51x2OiNCpGiASRuS+YNA4xHHRHhTbDo=

Server X : 4871355804744515205976212250393766354584896109692473021772491117721696883735035673432153598221753249992042089526706162901220401594166466831926219930877146558
Server Y : 5026058948106722611516311449372468937826180918866645483883605206287703217468368174419063547401569795955627245203008203991092043242186043679076827428816044782
SharedSecret LutQ40zPqxrf9aduolzD5oTLcLyJlfkEcxtNIDWEBmQ=

Java Source Code(can run on https://www.compilejava.net):

import java.lang.reflect.*;
import java.util.*;

import java.io.IOException;
import java.io.StringReader;
import java.math.BigInteger;
import java.security.*;
import java.security.interfaces.*;
import java.security.spec.*;
import java.text.MessageFormat;

import javax.crypto.*;
import javax.crypto.spec.*;
import javax.xml.parsers.*;

// one class needs to have a main() method
public class ECDHTest
{
      private static final String EC = "EC";
    private static final String EC_PARAM_SPEC_NAME = "secp521r1";
    private static final String SHA256 = "SHA-256";
    private static final String ECDH = "ECDH";
    public static void main(String[] args) {

        try {
            KeyTest();
        } catch (Exception e) {
            System.out.println(e.toString());

            e.printStackTrace(System.out);
        }
    }
    public static void KeyTest()throws Exception
    {
        //ServerSideTest();

        String clientSecretString = "2219285025076587881734163944765951664949675186777403178574059299188501213924848514092359154488536820511932392126399578571170916333994980346156346512122286111";
        String serverPointX = "4451545514874359902299158624438310022635978165655697097126344872030891198935714514315680031638033638457809873736532902539667967672541289019081100419964430099";
        String serverPointY = "3117123408335153723030634969320433663673333908311503930938506727201806384295739721251008570149972751600305211905288827467961338284313381940052563408260641664";
        ClientSideTest(clientSecretString, serverPointX, serverPointY);
        serverPointX = "4871355804744515205976212250393766354584896109692473021772491117721696883735035673432153598221753249992042089526706162901220401594166466831926219930877146558";
        serverPointY = "5026058948106722611516311449372468937826180918866645483883605206287703217468368174419063547401569795955627245203008203991092043242186043679076827428816044782";
        ClientSideTest(clientSecretString, serverPointX, serverPointY);
    }
    public static void ClientSideTest(String secretString, String serverPointX, String serverPointY) throws Exception
    {

        //PrivateKey clientPrivateKey;
        //PublicKey clientPublicKey;
        
        //Step 1: Initialize ECDH
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance(EC);
        keyPairGenerator.initialize(new ECGenParameterSpec(EC_PARAM_SPEC_NAME));
        KeyPair keyPair = keyPairGenerator.generateKeyPair();        
        ECPrivateKey dummyClientPrivateKey  = (ECPrivateKey)keyPair.getPrivate();
        ECPublicKey dummyClientPublicKey  = (ECPublicKey)keyPair.getPublic();
        ECPoint dummyClientPoint = dummyClientPublicKey.getW();

        BigInteger secret = new BigInteger(secretString);
        ECParameterSpec privateKeySpec = dummyClientPrivateKey.getParams();
        ECPrivateKeySpec clientPrivateKeyspec = new ECPrivateKeySpec(secret, privateKeySpec);
        KeyFactory keyFactory = KeyFactory.getInstance(EC);
        ECPrivateKey clientPrivateKey = (ECPrivateKey) keyFactory.generatePrivate(clientPrivateKeyspec);        
        ECPublicKeySpec clientPublicKeyspec = new ECPublicKeySpec(privateKeySpec.getGenerator(), dummyClientPublicKey.getParams());
        
        ECPublicKey clientPublicKey = (ECPublicKey) keyFactory.generatePublic(clientPublicKeyspec);
        ECPoint clientPoint = clientPublicKey.getW();
        System.out.println(String.format( "Secret   :%s", secretString));
        System.out.println(String.format( "Client X : %s\nClient Y : %s\n", clientPoint.getAffineX(), clientPoint.getAffineY()));

        ECPoint serverPoint = new ECPoint(new BigInteger(serverPointX), new BigInteger(serverPointY));
        
        ECPublicKeySpec serverPublicKeySpec = new ECPublicKeySpec(serverPoint, dummyClientPrivateKey.getParams());
        PublicKey serverPublicKey = keyFactory.generatePublic(serverPublicKeySpec);
        KeyAgreement keyAgreement = KeyAgreement.getInstance(ECDH);
        keyAgreement.init(clientPrivateKey);
        keyAgreement.doPhase(serverPublicKey, true);
        byte[] sharedSecret = keyAgreement.generateSecret();

        byte[] hashedSharedSecret = MessageDigest.getInstance(SHA256).digest(sharedSecret);
        System.out.println(String.format( "Server X : %s\nSErver Y : %s", serverPointX, serverPointY));
        System.out.println(String.format( "SharedSecret %s\n", Base64.getEncoder().encodeToString(hashedSharedSecret)));
    }

    public static void ServerSideTest() throws Exception
    {

        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance(EC);
        keyPairGenerator.initialize(new ECGenParameterSpec(EC_PARAM_SPEC_NAME));
        KeyPair keyPair = keyPairGenerator.generateKeyPair();        
        ECPrivateKey serverPrivateKey  = (ECPrivateKey)keyPair.getPrivate();
        ECPublicKey serverPublicKey  = (ECPublicKey)keyPair.getPublic();
        ECPoint serverPoint = serverPublicKey.getW();
        System.out.println(String.format( "Server Secret   :%s", serverPrivateKey.getS()));
        System.out.println(String.format( "Server X : %s\nServer Y : %s\n", serverPoint.getAffineX(), serverPoint.getAffineY()));
    }
}

PHP source:
----------------------------------

<?php
require 'vendor/autoload.php';

use Mdanter\Ecc\Crypto\EcDH\EcDH;
use Mdanter\Ecc\Crypto\Key\PrivateKey;
use Mdanter\Ecc\EccFactory;
use Mdanter\Ecc\Tests\AbstractTestCase;

class EcDHTest 
{
    
    private static function _keyDerivationFunction($math, $sharedSecret)
    {
        $binary = $math->intToString($sharedSecret);
        $hash = hash('sha256', $binary, true);
        return $hash;
    }
    const ECDHKeyValueXml = '<ECDHKeyValue xmlns=\'http://www.w3.org/2001/04/xmldsig-more#\'><DomainParameters><NamedCurve URN=\'urn:oid:1.3.132.0.35\' /></DomainParameters>
        <PublicKey><X Value=\'%s\' xsi:type=\'PrimeFieldElemType\' xmlns:xsi=\'http://www.w3.org/2001/XMLSchema-instance\' />
        <Y Value=\'%s\' xsi:type=\'PrimeFieldElemType\' xmlns:xsi=\'http://www.w3.org/2001/XMLSchema-instance\' /></PublicKey></ECDHKeyValue>';

    public static function test()
    {
        $generator = EccFactory::getNistCurves()->generator521();
        $adapter = EccFactory::getAdapter();

        $secretString = '2219285025076587881734163944765951664949675186777403178574059299188501213924848514092359154488536820511932392126399578571170916333994980346156346512122286111';
        $secretMultipler = gmp_init($secretString,10);

        $clientPrivateKey = new PrivateKey($adapter, $generator, $secretMultipler);
        $clientPublicKeyPoint =  $clientPrivateKey->getPublicKey()->getPoint();
		
        $clientKeyXValue = $adapter->toString($clientPublicKeyPoint->getX());
        $clientKeyYValue = $adapter->toString($clientPublicKeyPoint->getY());
        $clientPublicKeyString = sprintf(self::ECDHKeyValueXml, $clientKeyXValue, $clientKeyYValue);

        echo "Secret  : ".$secretString.PHP_EOL."Client X : ".$clientKeyXValue.PHP_EOL."Client Y : ".$clientKeyYValue.PHP_EOL.PHP_EOL;
		       
		$serverKeyXValueString = "4451545514874359902299158624438310022635978165655697097126344872030891198935714514315680031638033638457809873736532902539667967672541289019081100419964430099";
        $serverKeyYValueString = "3117123408335153723030634969320433663673333908311503930938506727201806384295739721251008570149972751600305211905288827467961338284313381940052563408260641664";
        static::CalculateSecret($generator, $adapter, $clientPrivateKey, $serverKeyXValueString, $serverKeyYValueString);
        $serverKeyXValueString = "4871355804744515205976212250393766354584896109692473021772491117721696883735035673432153598221753249992042089526706162901220401594166466831926219930877146558";
        $serverKeyYValueString = "5026058948106722611516311449372468937826180918866645483883605206287703217468368174419063547401569795955627245203008203991092043242186043679076827428816044782";
        static::CalculateSecret($generator, $adapter, $clientPrivateKey, $serverKeyXValueString, $serverKeyYValueString);
    }

    public static function CalculateSecret($generator, $adapter, $clientPrivateKey, $serverKeyXValueString, $serverKeyYValueString)
    {
        echo "Server X : ".$serverKeyXValueString.PHP_EOL."Server Y : ".$serverKeyYValueString.PHP_EOL;
        $serverPublicKey = $generator->getPublicKeyFrom(gmp_init($serverKeyXValueString, 10), gmp_init($serverKeyYValueString, 10), $generator->getOrder());
        $sharedSecretBeforeHash = $clientPrivateKey->createExchange($serverPublicKey)->calculateSharedKey();
        $sharedSecret = static::_keyDerivationFunction($adapter, $sharedSecretBeforeHash);
        echo 'SharedSecret '.base64_encode($sharedSecret).PHP_EOL.PHP_EOL;
    }
}

EcDHTest::test();

**Comment by afk11** [comment]
I've been looking into this, it was a padding issue, essentially the second example's X value has 519 bits in the number so is 65 bytes serialized, but the first has 521 bits (same as the generator521 order) and therefore is of the right size. 

 ```java
    byte[] sharedSecret = keyAgreement.generateSecret();
```
The bytes returned by the java function will be padded, even if the last byte is a totally zero byte, but the function intToString wasn't designed for that

```php
        $binary = $math->intToString($sharedSecret);
```

I use the following (from another codebase) for this, you would modify your key derivation to this:
```php
    private static function _keyDerivationFunction(\GMP $sharedSecret, GeneratorPoint $G) {
        $byteSize = NumberSize::bnNumBytes($G->getAdapter(), $G->getOrder());
        $two = gmp_init(2);
        $maskShift = gmp_pow($two, 8);
        $mask = gmp_mul(gmp_init(255), gmp_pow($two, $byteSize*8));

        $binary = '';
        for ($i = $byteSize - 1; $i >= 0; $i--) {
            $mask = gmp_div($mask, $maskShift);
            $binary .= pack('C', gmp_strval(gmp_div(gmp_and($sharedSecret, $mask), gmp_pow($two, $i * 8)), 10));
        }

        $hash = hash('sha256', $binary, true);
        return $hash;
    }
```
which returns the right key. I'll extract it into the GmpMath class..

**Comment by afk11** [comment]
@Daniel0r Hi there, this is one of the most interesting issues we've had recently, did you get it working in the end?

**Comment by Daniel0r** [comment]
Ho, @afk11 , thanks for following up.  Yes, we did resolve the issue.  Our customer figured out the same thing as you did.  We modified the int2string to get the padding right.  Sorry, forgot to post back before.
