### ISSUE TITLE
Caused by: Invalid S

### ISSUE THREAD

**Issue by adoley** [phpecc/phpecc#209]
Hi,
I am using  generator256k1

$generator = EccFactory::getSecgCurves()->generator256k1();

And sometimes I get below error
Caused by: Invalid S. Must be smaller than half the order 

**Sample error:**

Caused by: Invalid S. Must be smaller than half the order [79077169350175026522234251280531018405342103864524530556834425562603477199870][57896044605178124381348723474703786764998477612067880171211129530534256022184].

**Comment by afk11** [comment]
Can you provide the backtrace? Not sure where that comes from and quick search isn't giving me anything.

**Comment by adoley** [comment]
[details] => The creator's signature over the proposal is not valid, err Could not determine the validity of the signature, err CSP:500 - Failed verifing with opts [<nil>]

**Comment by afk11** [comment]
ECDSA doesn't mandate high or low S in signatures, so it's not a problem with this library. 

The service you are integrating with has added this requirement (I see Hyperledger's code contains the first error string you linked) so you should review the specification to understand why this is failing.

**Comment by adoley** [comment]
Thank u

**Comment by afk11** [comment]
For now, this snippet might get you running:

```php
<?php

use BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Signature\Signature;
use Mdanter\Ecc\Curves\CurveFactory;
use Mdanter\Ecc\Math\GmpMath;

require __DIR__ ."/vendor/autoload.php";

$generator = CurveFactory::getGeneratorByName('secp256k1');
$adapter = new GmpMath();
$oldSig = new Signature(gmp_init(1), gmp_init(1));

$r = $oldSig->getR();
$s = $oldSig->getS();
$halfOrder = $adapter->rightShift($generator->getOrder(), 1);

if ($math->cmp($s, $halfOrder) > 0) {
    $s = $adapter->sub($generator->getOrder(), $s);
}

$lowSSig = new Signature($sig->getR(), $s);

```

**Comment by adoley** [comment]
Thank u. It really helped.
