### ISSUE TITLE
Could not use existing private key

### ISSUE THREAD

**Issue by etienneroudeix** [phpecc/phpecc#220]
Hello,
I am trying to use an existing private key to sign a transaction.
However when I use `$key = $pemSerializer->parse($keyData);` I got the following error:
```
Fatal error: Uncaught FG\ASN1\Exception\ParserException: ASN.1 Parser Exception at offset 48: Can not parse content length (long form) from data: Offset index larger than input size in [...]/fgrosse/phpasn1/lib/ASN1/ASNObject.php on line 330

FG\ASN1\Exception\ParserException: ASN.1 Parser Exception at offset 48: Can not parse content length (long form) from data: Offset index larger than input size in [...]/fgrosse/phpasn1/lib/ASN1/ASNObject.php on line 330

Call Stack:
    0.0131     387320   1. {main}() send_raw_transaction.php:0
    0.1506    1971360   2. Tx->sign(???) send_raw_transaction.php:183
    3.0020    2366976   3. Mdanter\Ecc\Serializer\PrivateKey\PemPrivateKeySerializer->parse(???) send_raw_transaction.php:118
    3.0021    2367072   4. Mdanter\Ecc\Serializer\PrivateKey\DerPrivateKeySerializer->parse(???) [...]/mdanter/ecc/src/Serializer/PrivateKey/PemPrivateKeySerializer.php:54
    3.0091    2418288   5. FG\ASN1\ASNObject::fromBinary(???, ???) [...]/mdanter/ecc/src/Serializer/PrivateKey/DerPrivateKeySerializer.php:91
    3.0184    2481416   6. FG\ASN1\UnknownConstructedObject->__construct(???, ???) [...]/fgrosse/phpasn1/lib/ASN1/ASNObject.php:266
    3.0186    2481472   7. FG\ASN1\ASNObject::parseContentLength(???, ???, ???) [...]/fgrosse/phpasn1/lib/ASN1/UnknownConstructedObject.php:27
```

I investigated a bit and ended in `UnknownConstructedObject::__construct` doing `self::parseContentLength($binaryData, $offsetIndex);`.

From this the `$nrOfLengthOctets = $contentLength & 0x7F;` is greater than the data length and finally failed.

This is a pk (`$keydata`) sample : `673ec5224fa6a5cfe428f021f3edfb03d00e7ee40542982c07535eb5de9bae86`

Key was generated by an ethereum geth node.
Key details : 
```
{
  "address": "635128f079377bf95f4b679e232ae0e2507c1a42",
  "crypto": {
    "cipher": "aes-128-ctr",
    "ciphertext": "9be3bc24cdbfe36efea592b8992ced522bc9c7c9b41d41464e6aafe726597e9d",
    "cipherparams": {
      "iv": "c0093c9a1fe5b497f96de2b87850ccc9"
    },
    "kdf": "scrypt",
    "kdfparams": {
      "dklen": 32,
      "n": 262144,
      "p": 1,
      "r": 8,
      "salt": "96274c731469498dedeebc2e8fb2613d34a7fa70a6cc7d52f780636eaf40d8b0"
    },
    "mac": "93884929db6e243a1c9866ee4e0023af07c8838f8ce83503cea15e08ed927291"
  },
  "id": "32f5cf8d-f3ea-438e-a8e4-b473891b5391",
  "version": 3
}
```

I would appreciate if anyone can give me any clue :)

**Comment by afk11** [comment]
Ah, those serializers are for DER and PEM encodings. You mostly likely just want `$G->getPrivateKeyFrom(gmp_init($keyData, 16));` where $G is the appropriate generator for ethereum.

**Comment by afk11** [comment]
Just to update this issue, your $keyData is hex, whereas the serializer you are using is the PEM serializer, which assumes the base64 decoded data is DER. You are dealing with a raw private key here, so you should convert it as I mentioned above!

I'm going to close this due to inactivity, but feel free to open if you have any difficulties!
