### ISSUE TITLE
ECIES support

### ISSUE THREAD

**Issue by francislavoie** [phpecc/phpecc#231]
I found https://github.com/steveMcMann/ECIES, may or may not be complete, I'm not knowledgeable enough to make that determination right now.

Is it possibly in the cards for this lib to implement ECIES in the future?

**Comment by afk11** [comment]
Not likely I'm afraid, happy for someone else to maintain that part :) I don't really like adding to the API here without good reason.

**Comment by francislavoie** [comment]
The good news is I've since moved on from the company at which I would've used this :joy: 

No worries.
