### ISSUE TITLE
Point not in the curve

### ISSUE THREAD

**Issue by Spomky** [phpecc/phpecc#235]
Hi,

Can you please read the following issue: https://github.com/web-push-libs/web-push-php/issues/14
It looks like in some cases points are not considered in the curve when they should be.

Any idea?

**Comment by afk11** [comment]
Hmm, pretty strange. Do you have a recent trace of it happening? I'm not familiar with the protocol anyway, so direct links to code/functions would help. Also, I could UncompressedPointSerializer that second public key (BDtWy4HfhkfyXAJnP51PLsldXvRI8Gyj2OGDQbklvUCFBNBpyU/nJg0ytb4enzQc5DoLIGqllKeFLRpNDvvirgA=), so maybe I'm taking the wrong thing as input?

**Comment by Spomky** [comment]
Closing as it looks like the issue came from a double encoding.

**Comment by afk11** [comment]
Whew! That's good news!
