### ISSUE TITLE
Testing with Wycheproof

### ISSUE THREAD

**Issue by thaidn** [phpecc/phpecc#238]
Hi!

[Project Wycheproof](https://github.com/google/wycheproof) provides thousands of [test vectors](https://github.com/google/wycheproof/tree/master/testvectors) that have uncovered a lot of bugs in popular crypto libraries. Have you considered running it against this library?

Thanks!

**Comment by afk11** [comment]
Hi,

I have heard of the massive set of test vectors, I am definitely interested! It shouldn't be hard, I'll have a look in the next week or so. 

Thanks for the reminder!

**Comment by afk11** [comment]
Hi @thaidn, 

I have a summary of what we implemented for this issue. Originally I was overwhelmed as there's a lot of tests in the wycheproof project, ranging from simple tests, to tests for timing attacks and so on. It was hard to know where to start first.

I implemented analogues of tests which filter curves we don't have, and occasionally, some fixtures where we have decided to ignore that flag. (https://github.com/phpecc/phpecc/blob/9c69f721fe394d129be8f4461a5b8bfaf2f8a0e4/tests/wycheproof/EcdhTest.php#L199, https://github.com/phpecc/phpecc/blob/9c69f721fe394d129be8f4461a5b8bfaf2f8a0e4/tests/wycheproof/EcdsaTest.php#L218)

The PR introducing the tests and fixes is here and provides a summary of results: https://github.com/phpecc/phpecc/pull/254/files. You can glance through src and ignore the Exception stuff for the interesting parts (we had to add a few more exception types to assert the correct error was thrown). 

I wanted to ask, do the json test vectors test for everything, and are there other tests in wycheproof you'd suggest we prioritize reviewing?

**Comment by afk11** [comment]
We're testing with wycheproof now, closing
