### ISSUE TITLE
Secp256k1 ECDH key exchange between php and android

### ISSUE THREAD

**Issue by ZeroDice** [phpecc/phpecc#240]
I am having trouble getting the two to have the same shared secret, Android returns a byte array for the shared secret which I then base64 encode. I am aware that this should not be used as the actual key for encryption. On the phpecc side the shared secret is returned as a GMP integer, I have no idea how to convert this to a base64 encoded string that matches the one from Android. Since the two shared secrets are in different forms they can not be used, also i can not confirm that they are actually identical because of this.

The Android side code

```java
public static String getSharedSecret(PrivateKey myPrivate, PublicKey otherPublic){

        try {

            KeyAgreement keyAgreement = KeyAgreement.getInstance("ECDH", "SC");
            keyAgreement.init(myPrivate);
            keyAgreement.doPhase(otherPublic, true);

            byte[] sharedSecret = keyAgreement.generateSecret();
            return new String(Base64.encode(sharedSecret), "UTF-8");

        } catch (NoSuchProviderException e){

            e.printStackTrace();
            return "";

        } catch (NoSuchAlgorithmException e){

            e.printStackTrace();
            return "";
        } catch (InvalidKeyException e){

            e.printStackTrace();
            return "";

        } catch (UnsupportedEncodingException e){

            e.printStackTrace();
            return "";
        }

    }
```

Which returns something like: 
wxQFjNvmyai8yAlog6Y44RlyflxsW8cRuCDeNSK7jW0=

The php side code

```php

$adapter    = EccFactory::getAdapter();
$derPub     = new DerPublicKeySerializer();
$pemPub     = new PemPublicKeySerializer($derPub);
$pemPriv    = new PemPrivateKeySerializer(new DerPrivateKeySerializer($adapter, $derPub));

$alicePriv  = $pemPriv->parse(file_get_contents(__DIR__ . '/alice-secp256k1.pem'));
$bobPub     = $pemPub->parse(file_get_contents(__DIR__ . '/bob-pub-secp256k1.pem'));
$exchange   = $alicePriv->createExchange($bobPub);
$shared     = $exchange->calculateSharedKey();
```

Which returns something like:
88236380721315113214487272751771429956866021590683310398533077738186851716461

Is there a way to get these two to equate?

**Comment by afk11** [comment]
Comparing the two, they are equal, besides all the different encodings.
```
$ php -r 'echo bin2hex(base64_decode("wxQFjNvmyai8yAlog6Y44RlyflxsW8cRuCDeNSK7jW0="));'
c314058cdbe6c9a8bcc8096883a638e119727e5c6c5bc711b820de3522bb8d6d 
$ php -r 'echo gmp_strval(gmp_init("88236380721315113214487272751771429956866021590683310398533077738186851716461", 10), 16);'
c314058cdbe6c9a8bcc8096883a638e119727e5c6c5bc711b820de3522bb8d6d
```
There's one more step as well, which really needs to be illustrated in the docs (or fixed internally)..

https://github.com/phpecc/phpecc/blob/master/src/Math/GmpMath.php#L220

You should include this:
```php
$shared = $math->intToFixedSizeString($exchange->calculateSharedKey(), 32);
```

It's necessary because during the conversion of \GMP -> binary, there's a 1/256 chance the leftmost byte can be 0x00, so this function takes care of ensuring the number is fully padded (32 bytes always, not 21 bytes 1 time out of 256 and hard to debug)

**Comment by ZeroDice** [comment]
Thank you for the assistance, everything seems to be working perfectly now

**Comment by afk11** [comment]
Awesome, glad to hear! :+1:
