### ISSUE TITLE
PEM private key parse error

### ISSUE THREAD

**Issue by gaminn** [phpecc/phpecc#248]
Hi,
when parsing PEM private key using

`$pemSerializer = new PemPrivateKeySerializer(new DerPrivateKeySerializer($adapter));
$keyData = file_get_contents('../../../private.pem');
$key = $pemSerializer->parse($keyData);`

I get error:

`Uncaught Error: Class 'FG\\ASN1\\ASNObject' not found in /data/web/virtuals/139054/virtual/www/subdom/api/vendor/mdanter/ecc/src/Serializer/PrivateKey/DerPrivateKeySerializer.php:91`

With version 0.4 this code worked, with latest version this error is displayed.

**Comment by afk11** [comment]
Glad you got this sorted! It can be nice for others to see what the solution was to  issue.

I know that object is new in the later versions, to me it seems your deps could have been out of date? (Had new phpecc version but not phpasn somehow?)
