### ISSUE TITLE
Is it possible to add other curves such as secp128r1

### ISSUE THREAD

**Issue by jithin-pits** [phpecc/phpecc#249]
Is it possible to add curve such as secp128r1, if so please suggest the steps to implement the curve

**Comment by afk11** [comment]
For some stuff it would be possible to just create the Curve and Generator you wanted out of your curves parameters, and most of the crypto operations would work, but some the Serializer classes carry some private state that isn't easy to change. You'd likely run into problems there, so it depends what you are doing.

Perhaps we could consider adding methods to register new curves that aren't officially part of the library at some point.

**Comment by jithin-pits** [comment]
Thank you so much, anyway I'll go with "secp256k1" which is already included here, please suggest how to use ( choose ) secp256k1 as the examples are for nist, thanks in advance.
