### ISSUE TITLE
Invalid key length for secp256k1

### ISSUE THREAD

**Issue by jithin-pits** [phpecc/phpecc#250]
We are using the code to generate public key using secp256k1

$adapter = EccFactory::getAdapter();
$generator = EccFactory::getSecgCurves()->generator256k1();

$private = $generator->createPrivateKey();
$public = $private->getPublicKey();

$derPubSerializer = new DerPublicKeySerializer($adapter);
$derPub = $derPubSerializer->serialize($public);

var_dump(bin2hex($derPub));exit;

what we get is:
3056301006072a8648ce3d020106052b8104000a034200044c3ed2133f38373c37e8f18066ad2df906fd1292da6e2672080bd50dc8d31e5314f0d1390ffa35f5e185f22686e6298c7165c7895104baff562ce8677cbf27ec

what we expect is:

044c3ed2133f38373c37e8f18066ad2df906fd1292da6e2672080bd50dc8d31e5314f0d1390ffa35f5e185f22686e6298c7165c7895104baff562ce8677cbf27ec
(which is a valid key of length of 130 charecters and starts with 04 in hex )

**3056301006072a8648ce3d020106052b8104000a034200** in 

**3056301006072a8648ce3d020106052b8104000a034200**044c3ed2133f38373c37e8f18066ad2df906fd1292da6e2672080bd50dc8d31e5314f0d1390ffa35f5e185f22686e6298c7165c7895104baff562ce8677cbf27ec

always get appended to the generated public key.

if we generate again, we get a new key with **3056301006072a8648ce3d020106052b8104000a034200** appended to the key

we want public key in hex, what are we missing, please correct if we are wrong.

**Comment by jithin-pits** [comment]
Ok we get it .. 

$derPubSerializer = new DerPublicKeySerializer($adapter);
$derPub = $derPubSerializer->serialize($public);

var_dump(bin2hex($derPub));exit;

should be changed to 

$serializer = new UncompressedPointSerializer();
$serialized = $serializer->serialize($public->getPoint());

var_dump(bin2hex($serializer));exit;

**Comment by afk11** [comment]
There's compressed and uncompressed point serializers which deal with the format you describe. The DerPublicKeySerializer is for an ASN1 format which includes the curve parameters (https://tools.ietf.org/html/rfc5480#page-3) https://lapo.it/asn1js/#MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETD7SEz84Nzw36PGAZq0t-Qb9EpLabiZyCAvVDcjTHlMU8NE5D_o19eGF8iaG5imMcWXHiVEEuv9WLOhnfL8n7A

**Comment by jithin-pits** [comment]
Dear @afk11 

Thank you so much.
