### ISSUE TITLE
ECDH: How to get a shared secret with a public key as hex string

### ISSUE THREAD

**Issue by marcosaftertype** [phpecc/phpecc#257]
Using version 0.4.7 to support PHP5.6.

Following this example I see how to generate a shared secret...

https://github.com/phpecc/phpecc/blob/e465bf84a81898310a896e8cb26bd2f165ddc025/examples/ecdh_exchange.php#L25

However in my use case I have the public key of 'bob' as a hex string. Can you point me in the right direction to load a hex string public key to be used in the exchange?

**Comment by afk11** [comment]
You want the Point serializers, not the DER/PEM Serializers: https://github.com/phpecc/phpecc/tree/master/src/Serializer/Point

**Comment by marcosaftertype** [comment]
Thanks @afk11, your comment gave me traction to solve this.

In case someone else stumble upon this, here is what I did at the end:

```php
$pub_key_hex = "02a0ba93d7937cef537ce1cca1a4255414f0ac8c8fff32846351f0dc9bdec4e9cd";
$adapter = EccFactory::getAdapter();
$generator = EccFactory::getSecgCurves()->generator256k1();
$curve = EccFactory::getSecgCurves()->curve256k1();

$point_serializer = new CompressedPointSerializer($adapter);
$pub_key_point = $point_serializer->unserialize($curve, $pub_key_hex);
$public_key = new PublicKey($adapter, $generator, $pub_key_point);

$ephemeral_key = $generator->createPrivateKey();
$exchange = $ephemeral_key->createExchange($public_key);

// ...
```
