### ISSUE TITLE
Php 7.3 support

### ISSUE THREAD

**Issue by chaitanya-c** [phpecc/phpecc#258]
Php requirements can be supported till 7.3

**Comment by afk11** [comment]
Thanks, you're quite right. Bumped nightly to 7.4snapshot per https://travis-ci.community/t/add-php-7-4-branch-to-test-against/2179/4, and the 'extra' tests run on 7.2 now run on 7.3

**Comment by chaitanya-c** [comment]
Can you we update composer as well

**Comment by chaitanya-c** [comment]
@afk11 Any update one this

**Comment by afk11** [comment]
@chaitanya-c sorry, I was wondering about this, why exactly is that necessary?

Maybe I misunderstood the issue, 7.3 should already supported by composer? 
https://github.com/phpecc/phpecc/blob/master/composer.json#L27

**Comment by kiamlaluno** [comment]
I read @chaitanya-c comment as a request to increase the minimum PHP version required from PHPECC. I understand "Can we update composer as well?" as "Can we update composer.json as well?"

**Comment by afk11** [comment]
@kiamlaluno: I don't believe it's necessary to use the library on 7.3 - people are using the library on 7.0/7.1/7.2/7.3, and I'm not convinced why we would want to raise the minimum version for composer?

**Comment by kiamlaluno** [comment]
@afk11 	I don't believe that is a necessary change. I gave my interpretation of  <em>Can you we update composer as well</em> as <em>update composer</em> doesn't make sense to me. (Nor does a request to increase the required PHP version.)

**Comment by afk11** [comment]
Thanks :+1: closing for now
