### ISSUE TITLE
Verifying payload against known public key

### ISSUE THREAD

**Issue by alexander-morris** [phpecc/phpecc#260]
This package looks awesome for closed loop situations, but I've been trying to use it to verify payload signatures and I think I might be missing something.

I've got a hex-formatted public key and a secp256k1 payload and signature. I'd like to use the verify functionality ( /ecc/src/Crypto/Signature/Signer.php -> verify ) but it requires that the public key is first formatted as /ecc/src/crypto/key/PublicKey.php, but this seems to require that I somehow create a PointInterface object from my hex public key.

Is there a way to do this that I'm not seeing?

**Comment by afk11** [comment]
https://github.com/phpecc/phpecc/blob/master/src/Serializer/PublicKey/Der/Parser.php#L105

You need the PointSerializer for that, the DER/PEM serializers refer to a different encoding.

**Comment by afk11** [comment]
Closed due to inactivity, reopen if needed
