### ISSUE TITLE
Generate signature from PKCS#8 (itunes)

### ISSUE THREAD

**Issue by mpoiriert** [phpecc/phpecc#261]
Hi !

I am trying to do this using the library:

https://developer.apple.com/documentation/storekit/in-app_purchase/generating_a_signature_for_subscription_offers

Can someone provide any help ?

**Comment by afk11** [comment]
The PKCS8 standard defines a way to encrypt an ASN1 object representing a private key. Unfortunately no-one's written a decoder/decrypter that works with this library yet - but there's a composer package which seems to support pkcs8 (using openssl), which might suit your purpose instead. https://packagist.org/packages/sop/pkcs8 

Alternatively, you could write your own decoder - PKCS8 is described here: https://tools.ietf.org/html/rfc5208. Section 5 explains the structure of the ECPrivateKey, and the binary representation of this will be encrypted, and embedded in another structure described in section 6. 

We have a decoder for a different private key format in the library, it's probably a good thing to check out. https://github.com/phpecc/phpecc/blob/master/src/Serializer/PrivateKey/DerPrivateKeySerializer.php

**Comment by Spomky** [comment]
I will be happy to try to implement such decoder.
[I created a small class may help](https://github.com/web-token/jwt-framework/blob/v1.3.5/src/Component/KeyManagement/KeyConverter/ECKey.php) (used for JWK loading).

Do you have some sample keys to share?

**Comment by mpoiriert** [comment]
Thanks @afk11 I'll give a check to the other library I am a big in a rush right now.

@Spomky I can provide you with a .p8 file so you can give it a try, I will validate if it's working in the full flow I need when you have something that can be tested. How can I provide you the file ?

**Comment by Spomky** [comment]
@mpoiriert we can discuss [on Gitter](https://gitter.im/Spomky)

**Comment by afk11** [comment]
It looks like this was resolved, but reopen if needed :+1:
