### ISSUE TITLE
Get K Value

### ISSUE THREAD

**Issue by fajrirasyid** [phpecc/phpecc#262]
Excuse me, Im still learning about this method, I need help for getting K value from Sign function in signature.php.
I can't get the K value with echo, thanks in advance.

**Comment by afk11** [comment]
Hi. Are you using creating_signature.php or verify_signature.php? creating_signature.php calculates k https://github.com/phpecc/phpecc/blob/master/examples/creating_signature.php#L39 directly in the code but verify_signature.php only has the signature (r,s), the message hash, and public key.
https://github.com/phpecc/phpecc/blob/master/examples/verify_signature.php#L34

**Comment by fajrirasyid** [comment]
I'm using both of them. I want to check manually the value with print them (k,r,s) but can't use echo to print. I'm intent to check the signature value before it was encode with base64.

**Comment by afk11** [comment]
> but can't use echo to print. 

you probably need to call gmp_strval first

**Comment by fajrirasyid** [comment]
Finally, we (@debidwitamayusup and me) can print r and s value with
`$test = new ReflectionObject($signature);
				        $printRvalue = $test->getProperty('r');
				        $printSvalue = $test->getProperty('s');
				        $printRvalue->setAccessible(true);
				        $printSvalue->setAccessible(true);
				        echo "r: ".$printRvalue->getValue($signature);
				        echo "r: ".$printRvalue->getValue($signature);
                                        `
But i still can't return and print this value [https://github.com/phpecc/phpecc/blob/master/src/Crypto/Signature/Signer.php#L81-L86](url)
to check manually verifying process.

**Comment by afk11** [comment]
Err, why are you using reflection when you could call $sig->getR() / $sig->getS()?

**Comment by fajrirasyid** [comment]
I'm sorry because my lack of knowledge. I don't know how to use gmp_strval, so i was searching for another way to get these value. But thanks now i know.

I just want to check manually the signature generation and verification in these code are same with the theory (D. Hankerson's Book - Guide to Elliptic Curves). The variable is same but i can't figure it out, how to show each value (c, u1, u2, xy, v) in verification process. In the end of verification process, there's just comparison between v and r value with constant time.

**Comment by afk11** [comment]
OK - c, u1, u2, and v are all GMP objects, so gmp_strval will work for those. xy is a PointInterface https://github.com/phpecc/phpecc/blob/b95f25cc1bacc83a9f0ccd375900b7cfd343029e/src/Primitives/Point.php#L152, which has functions to return the (x, y) coordinates as a GMP object. 
<?php
echo "c: " .gmp_strval($c, 10) . "\n";
echo "u1: " .gmp_strval($u1, 10) . "\n";
echo "u2:  " .gmp_strval($u2, 10) . "\n";
echo "xy.x " .gmp_strval($xy->getX(), 10) . "\n";
echo "xy.y " .gmp_strval($xy->getY(), 10) . "\n";
echo "v: ".gmp_strval($v, 10)."\n";
```

**Comment by fajrirasyid** [comment]
Thank you so much for helping me, i hope i can develop it soon.
