### ISSUE TITLE
How are the r and s value encoding process to become Signature value?

### ISSUE THREAD

**Issue by fajrirasyid** [phpecc/phpecc#263]
@afk11 I'm sorry if i bother you. I have got the r,s value, but the signature value is different with r,s value. I have encoded r,s manually with base 64 encoding but the result still different. So, how is the encoding process actually work?
![image](https://user-images.githubusercontent.com/18899195/57979173-06aee200-7a44-11e9-86c9-d715b400f5e7.png)

**Comment by afk11** [comment]
It's an ANS.1 encoding: https://github.com/phpecc/phpecc/blob/master/src/Serializer/Signature/Der/Formatter.php

maybe paste the privkey / msg / k value  / signature, and what you expected to get?

**Comment by afk11** [comment]
This issue has been inactive for some time. If you still need help feel free to re-open!
