### ISSUE TITLE
Point Multiplication in Signer.php

### ISSUE THREAD

**Issue by rsydwidiadi** [phpecc/phpecc#264]
What method is used in point multiplication for signature generation? How to compute a point with k variable? I think it's not usual arithmetic multiplication. I'm trying to check point value before and after multiplication. Thanks. https://github.com/phpecc/phpecc/blob/master/src/Crypto/Signature/Signer.php

**Comment by afk11** [comment]
Point::mul is the method used in point multiplication for signature generation https://github.com/phpecc/phpecc/blob/master/src/Primitives/Point.php#L254

Regarding _usual arithmetic multiplication_ - points are composite data types, so there needs to be a method to perform multiplication. The basics can be found in any ECC guide, and the specifics of what we've implemented are discussed here: https://github.com/phpecc/phpecc/issues/16

> I'm trying to check point value before and after multiplication.

Could you explain what for? That's simple scalar multiplication, something we have lots of tests for :)

**Comment by rsydwidiadi** [comment]
> Could you explain what for? That's simple scalar multiplication, something we have lots of tests for :)
Nothing, I just can't understand the multiplication process. So, the multiplication method that used in this project is double and add or double and add-always?

> GeneratorPoint::mul. See tests or examples for how to get the right Generator.
Which file to pick so i know the right Generator to use?

**Comment by afk11** [comment]
> So, the multiplication method that used in this project is double and add or double and add-always?

Yep

> Which file to pick so i know the right Generator to use?

Example: https://github.com/phpecc/phpecc/blob/master/examples/key_generation.php#L10 

For supported curves/generators see NistCurves / SecgCurves here: https://github.com/phpecc/phpecc/tree/master/src/Curves

**Comment by rsydwidiadi** [comment]
Okey thanks a lot😊
