### ISSUE TITLE
Is it possible to parse a private key from a hex value (similar to parseKey for public keys)

### ISSUE THREAD

**Issue by ddauchy** [phpecc/phpecc#266]
In mdanter/ecc/src/Serializer/PublicKey/Der/Parser.php parseKey there is a function parseKey.  I pass it a generator (setup to be the curve I want), and the key (hex string).  It creates a PublicKey object.

I have a hex value for a private key and I'd like to be able to create a Private Key object.  But I see no similar Parser class for private keys.  Am I missing it or does it not exist?

Thank you!

**Comment by afk11** [comment]
`gmp_init($privKey, 16)` after validating the string is exactly 64 bytes of hex and then pass the resulting GMP object to this method https://github.com/phpecc/phpecc/blob/master/src/Primitives/GeneratorPoint.php#L105

**Comment by ddauchy** [comment]
Thank you very much sir!
