### ISSUE TITLE
Console improvements

### ISSUE THREAD

**Issue by aztech-dev** [phpecc/phpecc#43]
-- note: this is more a reminder for me to do it than to raise a real issue, but my free time is limited so can't tackle it right now --

Todo once #41 is merged

- [x] Parse full PEM data with headers and new lines
- [ ] Sign message
- [ ] Verify signature
- [x] Add options to read files instead of inline data
- [x] Add options to configure curve used for generated keypairs (currently only NIST P256/SECP 256R1)
- [x] Add list supported curves command
- [x] Add support for DER encoded files

**Comment by btcdrak** [comment]
I assume the rest of this ticket goes to future version? 0.4 or 0.3.x?

**Comment by aztech-dev** [comment]
Can be in a 0.3.x release as it wont be breaking anything... I'm hoping to clear up some time in the coming weeks to tackle the sign/verify commands.

**Comment by afk11** [comment]
I was working on this, but it started to open a can of worms, and we were already long due 0.3.0, so figured I'd save it for after. 

I was thinking an EcParams file is the best way to avoid many many parameters to the sign/verify commands. But it requires Signer knowing about the hash function being used + a few other things.

**Comment by afk11** [comment]
Closing, belongs over in phpecc/console
