### ISSUE TITLE
Missing test vectors for curves

### ISSUE THREAD

**Issue by aztech-dev** [phpecc/phpecc#47]
Only NIST P-192 curve is currently tested.

- [X] Refactor testsuite to load test vectors from data files -- YAML based loader
- [X] Add missing test vectors
  - [X] NIST P-192
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA / RFC6979
  - [X] NIST P-224
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA / RFC6979
  - [X] NIST P-256
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA / RFC6979
  - [X] NIST P-384
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA / RFC6979
  - [X] NIST P-521
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA
  - [X] SECP-256K1
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA / RFC6979
  - [X] SECG-256R1 (technically identical as NIST-P256, but loaded via different code path, so standalone tests)
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA
  - [X] SECG-384R1
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA
  - [X] SECP-112R1
    - [X] Keypairs
    - [X] Diffie Hellman Key exchange
    - [X] DSA

Edit: updated by @afk11 - all complete

**Comment by btcdrak** [comment]
bump

**Comment by aztech-dev** [comment]
Jeez, you're a real slavedriver ! 

Planned to handle this one next, hopefully by the end of the week.

**Comment by aztech-dev** [comment]
I've issued a first P/R which adds test vectors for public key generation for all the NIST curves.

All data is from http://point-at-infinity.org/ecc/nisttv.

I'll try to get the rest wrapped within the week.

**Comment by afk11** [comment]
Just to add some notes to this, I've added the rest of the RFC6979 test vectors which go through cases where the hash length is much larger than the integers used on the curve. 

I believe all that's left are the DH test vectors. I am a little worried about the base64 encoding pre-encryption, and using sha256() on sharedKey->getX() to produce the shared secret - it may mean we can't use their vectors.. I'll check it out later.

**Comment by btcdrak** [comment]
Are we going to finish this in 0.3.x?

**Comment by aztech-dev** [comment]
I don't think it's a blocker for 0.3.0 if that was the question :)

**Comment by afk11** [comment]
Yes - there will be a fix in 0.3.x to make HmacRandomNumberGenerator work with a curve of 521 bits keysize, since the vectors won't pass for that at the moment. 

As I mentioned above for EcDH, I think our base64_encode() usage, using sha256 on the key, needs some review. Odds are it won't work with other implementations because of this, or we just won't find test vectors.

**Comment by afk11** [comment]
Whoop whoop, this is fixed, we test everything* :) 

(*Besides secp112r1 with the HMACRNG. No such test vectors exist, and loath generating one for the sake of it)
