### ISSUE TITLE
Include some helper functions

### ISSUE THREAD

**Issue by afk11** [phpecc/phpecc#74]
recoverXfromY, point compression during serialization. Todo for me.

**Comment by aztech-dev** [comment]
I may have a partial implementation of a CompressedPointSerializer somewhere, though never got around to finish it. Want me to push it so you can start off there ?

**Comment by afk11** [comment]
Yeah that'd be cool!

**Comment by afk11** [comment]
Introduced CompressedPointSerializer in master. Also added a method to do the heavy-lifting:

CurveFpInterface::recoverYfromX(bool $wasOdd, \GMP $x)
