### ISSUE TITLE
Direction for 0.4.0

### ISSUE THREAD

**Issue by afk11** [phpecc/phpecc#83]
- [x] EcParamsSerializer (to ecparams file which contains the OID).
 - [ ] EcParamsExplicitSerializer (to ecparams file which contains the explicitly named parameters).
 - [ ] Console: Sign/Verify messages.
 - [ ] Console: Generate an ECParams file.

Reading over the parameters specification, https://tools.ietf.org/html/draft-ietf-pkix-ecc-pkalgs-01#section-3, it seems we can specify a hash function to use in the explicit parameters file - otherwise the default should be SHA1. Will 

Also in that document is a full specification of all the necessary types when generating a parameters file. I'm writing small classes to convert our types into theirs, instead of serializing everything - makes sense in the long run I think.

**Comment by afk11** [comment]
There are some good RFC's when you find them :) Anyway, looking for feedback on how to approach the above tasks! Especially @aztech-dev if you're around, as you've worked with fgrosse/asn.1 already!

A few off the cuff questions - what is a cofactor, and do we need one? :D Some googling tells me that it restricts the curve if it's not 1. So not sure if we should introduce this to the NistCurves and SecgCurves - it seems a default of one might be fine, but looking for thoughts on this.

I'm asking because when openssl is dumping curve parameters there's an optional parameter for the cofactor, and for the hashing algorithm.

Since we haven't started including hash functions in Curves yet, the NamedCurveExplicitSerailizer just sets this to sha1 by default (as per the docs). But I am thinking it's probably a good idea to expose this, since a hashing algorithm is used by EcDH and ECDSA and is as much a domain parameter as your choice of curve/generator/etc.

I've added a HashAlgorithmOidMapper, which largely mirrors CurveOidMapper, but instead of a curve it returns a callable for the hashing algorithm you gave it (along with the lookup functions for the OID/hash size). Seems we could have a default hashing algorithm just to make things work, but still allow people to customize that. 

What lead me to this is trying to dump the ec parameters so that it's compatible with openssl. I'd like to expose a similar feature set (eg, specifying the curve by it's name or the parameters file). 

Have a WIP, but the explicit parameters isn't really working yet: #84 

@btcdrak @rubensayshi ?

**Comment by afk11** [comment]
Just to correct myself - the ecparams stuff compatible with ASN.1 structures, not just openssl. 

I mention openssl because the functionality we're exposing through the console is largely similar to openssl (message signing/verification, dumping ec params, using ec params files to decide the curve to use, etc), and it'd be good to shoot for all of that. 

That said, it requires yet another BC break to introduce before 0.3.0, and it's mostly because I'd like the sign/verify console commands in there, which need to extract all relevant domain parameters - the cofactor and hashing algorithm from the params file. 

I know both me and @rubensayshi are itching for 0.3.0 - so could leave this for a later release? What do yous think?

**Comment by btcdrak** [comment]
Any user facing API BC breaks after 0.3.0 will have to wait for 0.4.0. You can add more features to 0.3.x so long as there are no user facing API breaks. That's why I've been quite tight on closing inheritance APIs by making default visibility `private`.

**Comment by aztech-dev** [comment]
To add to your list, I think we should aim for adding param info to the curve classes in 0.4.x. Currently, all code is based off guessing the actual key sizes in multiple places (namely, point multiplication, hmac, anything that uses `Mdanter\Ecc\Util\NumberSize`), and I'm not too fond of that (there are some edge cases where it fails).

**Comment by afk11** [comment]
Yes absolutely. The hash function should be known as well as well. It was my blocker on adding the sign/verify commands, I figured there'd be a nicer way to do it, but it would probably change quite a lot of the API.

**Comment by afk11** [comment]
This stuff was moved to phpecc/x509
