### ISSUE TITLE
MessageFactory should not be required for EcDH

### ISSUE THREAD

**Issue by dol** [phpecc/phpecc#91]
The MessageFactory introduced @afk11 in this [commit](https://github.com/mdanter/phpecc/commit/7ad58016051443e604402db82f01ec1c7f485c4f) is only needed for the encryption/decryption of information. If the EcDH class is only used for the key exchange and not the encryption part, a MessageFactory has always be passed in.
An other issue with this change is that the PublicKeyInterface for a [PrivateKey exchange](https://github.com/mdanter/phpecc/commit/7ad58016051443e604402db82f01ec1c7f485c4f#diff-edb3a091e01a394bdbdc1afc45991755R106) is option. But the recipientKey is [always required](https://github.com/mdanter/phpecc/blob/983212c0b1c6f573192b8afd98c5a67eddc1ed9c/src/Crypto/EcDH/EcDH.php#L212).

In addtion, the current example in the README.md is outdated:
```php
// ...
$bobDh = $bob->createExchange($alice);
$messageForBob = $bobDh->decrypt('... the encrypted message... too lazy to actually generate the encoded message');
```

IMHO the MessageFactory should be passed in as optional parameter into the EcDH constructor or passed as required parameter into encrypt/encryptFile and decrypt/decryptFile.

The test case [EcDhMultiPartyTest.php](https://github.com/mdanter/phpecc/blob/983212c0b1c6f573192b8afd98c5a67eddc1ed9c/tests/unit/Crypto/EcDhMultiPartyTest.php) is a good example of a MessageFactory initialisation, that is never been used.

**Comment by aztech-dev** [comment]
Good point. Personally, I'd lean towards passing MessageFactory as an argument to the encrypt/decrypt methods (as it's not required for EcDH to function properly).

Regarding the recipientKey optional argument, it was already optional before that commit. The reasoning behind it is that you still have an opportunity to set the recipient key later on (ie, you may not already have that key when creating the exchange), before calling calculateSharedKey(). However, the factory method is clearly lacking a null check :)

**Comment by afk11** [comment]
Hey, cheers for the message!

You're probably right about this. I don't make use of the EcDH functionality, so others may wish to voice their thoughts here, but I'd agree the encryption (and hence requirement for MessageFactory) to be moved elsewhere. There are other uses for EcDH, and for encryption it's not limited to using rijndael-256. 

On the README, I think it mentions somewhere that the examples aren't consistent with composer. Might submit a fix-up PR today if I get to it.

**Comment by dol** [comment]
Oh, nice. @afk11 and @aztech-dev you are faster than Speedy Gonzales :mouse:

**Comment by aztech-dev** [comment]
:)

@afk11 I think that can be a good move. If I recall correctly, the encrypt/decrypt methods in EcDH are legacy. However, that's a BC so they should probably be maintained and deprecated until the next major version.

**Comment by afk11** [comment]
Same goes for removing MessageFactory from the constructor right now; but I'll add it to the list of breaks. 0.4.0 won't be too far away at this stage!

**Comment by afk11** [comment]
Fixed in master
