### ISSUE TITLE
PHPASN1 is now >PHP5.6 only

### ISSUE THREAD

**Issue by afk11** [phpecc/phpecc#96]
And this wouldn't affect us besides the fact I need it's Integer class that can handle big-int's. I use the latest release in my recent series of PR's #92 #93 #94 #95 - in DerSignatureSerializer (not for anything exotic like cert's). 

What do people think about abandoning older versions? They're nearing end of support, so perhaps this is fine. I forgot that tests would fail on my builds, since the required version isn't supported on PHP 5.4 / 5.5

**Comment by btcdrak** [comment]
Anyone using these libraries is going to have control over their servers anyway...

**Comment by afk11** [comment]
Yeah - I expect it's fine. With #91 we'll have a break anyway. I'll bump the version requirements of my work, and save it for the next major release.

**Comment by afk11** [comment]
Just saw PHP5.5 is EOL'd in a month, we can resume tracking the latest PHPASN1 after that.

**Comment by afk11** [comment]
Fixed in master
